@startuml Mortgage_Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
LAYOUT_WITH_LEGEND()

title System Context diagram for Mortgage Portal

Enterprise_Boundary(DigitalFinTechyBank, "DigitalFinTechyBank") {
    Person(Applicant, "Applicant", "Might be a customer or a prospect customer")
    System(MortgagePortal, "Mortgage Portal", "Allows applicants to fill in mortgage applications and apply for loan")


    System_Ext(ComArch, "Complex Archive (ComArch)", "Provides an archive for important documents")
    System_Ext(CoreBanking, "Core Foundation Banking Platform Arena", "Provides core banking services like loan accounts")
    System_Ext(CreditKarma, "Credit Karma", "Provides credit scoring of norwegian citizens and property valuation")
    System_Ext(SigningDog, "SigningDog", "Provides electronic signing") 
    System_Ext(KnotMobility, "Knot Mobility", "Provides a REST API for sending sms")

    Rel(Applicant, MortgagePortal, "Fills in personal and property information")
   
    Rel(MortgagePortal, CreditKarma, "scores and applicant using")
    Rel(MortgagePortal, KnotMobility, "notifies applicant about decision and send esigning link using")
    Rel(MortgagePortal, CoreBanking, "creates loan account and registrers collateral in")
    Rel(MortgagePortal, SigningDog, "checks for newly signed documents at")
    Rel(MortgagePortal, ComArch, "stores signed documents in")

    Rel(KnotMobility, Applicant, "notifies applicant about decision and send esigning link using")
}

@enduml
